### ISSUE TITLE
Feature request: absolute TTL

### ISSUE THREAD

**Issue by Beanow** [avoidwork/tiny-lru#11]
My use-case for this is as a caching layer in front of an external **authoritative** service. In order to guarantee changes are reflected everywhere after a certain amount of time an absolute TTL is required.

For example `max = 50, maxTTL = 24h`
To guarantee that cached data is updated at least once every 24h.

The current TTL option does not provide for this as a `get` would bump the TTL allowing for indefinitely stale data.

**Comment by avoidwork** [comment]
i like it!

**Comment by avoidwork** [comment]
The new `expire` property, or 4th parameter for the factory, will remove an item regardless of a `ttl` timer.

**Comment by Beanow** [comment]
Nice :D thanks for looking into it.
I had a scroll through the implementation and have a question about it.

It looks as though evict / remove does not clear the expire timeout. So if fresh data from the authoritative service was readded later, it would expire sooner than the 24h.

Reset also seems to dereference, not clear the timeout.

**Comment by avoidwork** [comment]
doh, forgot about evict; probably shouldn't rush this stuff during the work day :D I'll take care of em now.

**Comment by avoidwork** [comment]
Fixed with https://github.com/avoidwork/tiny-lru/commit/bbbfacbef590f82b5f5221e0b1d1936e1196a8b5

**Comment by Beanow** [comment]
Thank you :tada: I'll be deploying this in the wild.

**Comment by franciscop** [comment]
Hi @avoidwork, awesome library here!

I have a similar issue; I am caching URLs and would like the oldest one that was read to be removed if there are too many. However, I would also like a maximum expiration period for each one to make sure that the data is fresh. Sounds like @Beanow situation!

So the conditions to remove an item are any of these:

- Too many items; remove the last one by `access_time` (NOT by `expiration_time`).
- Item too old; remove the old items to make sure the data stays fresh when the `expiration_time` is over.

Just wanted to make sure I understand how `expire` works.

**Comment by avoidwork** [comment]
Hi @franciscop,

The `ttl` property could be thought of as an early/soft expiration which will reset if reused, & the `expire` property is finite lifespan of the item in the cache, which will not reset upon access/use.

I should've named `ttl` something else, because it doesn't behave as you would expect in comparison to other products, it's a 'soft' expiration; when I made it I wasn't trying to force things out based on time 😬

**Comment by avoidwork** [comment]
A way to use both would be to have `expire = n & ttl = expire / 2`
