### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by GideonAgboba** [avoidwork/tiny-lru#110]
Using  { node: 'v16.16.0', npm: '9.6.4' } 
I get  the below error
```
/node_modules/tiny-lru/dist/tiny-lru.js:178
   }export{lru};
    ^^^^^^
   SyntaxError: Unexpected token 'export'
```

Extra: this package is required by `maxmind`  which is a dependency of `@maxmind/geoip2-node`

**Comment by avoidwork** [comment]
thanks for reporting; this appears to be a 'working as designed' based on the package.json behavior for 'main'; it just happens to conflict with the 'exports' key, so in your case you're getting the esm file (.js) instead of the cjs file (.cjs).

**Comment by avoidwork** [comment]
I can't recreate this with just tiny-lru:

```console
PS C:\Users\jason\Projects\x> node -v
v16.16.0
PS C:\Users\jason\Projects\x> cat .\index.js
const {lru} = require('tiny-lru');
const cache = lru();
console.log(cache.size);
PS C:\Users\jason\Projects\x> node .\index.js
0
PS C:\Users\jason\Projects\x>
```

**Comment by tuxmachine** [comment]
Bumping jest to v28+ should resolve the issue, it added support for the `package.json#exports` specification.

**Comment by naugtur** [comment]
Hi. I just stumbled upon this.
Multiple tools fall for this. `main` is intended to point to the CommonJS version AFAIK and it'd be nice to put the `.cjs` extension there. It would definitely help engines and environments that don't support exports field and therefore likely also ESM.

**Comment by avoidwork** [comment]
`main` is simply the default file to load, if an extension is not provided it goes through it's own enums. the `.cjs` was used in `10.x.x` and now that esm is viable it's time to let the tooling sort out this giant mess.

Upgrade your tool chain if you have a problem, or switch to tools that work.

**Comment by castarco** [comment]
Hi, even though this "works" in very well configured environments, it's highly problematic in legacy environments. And there is an actual easy fix for that. I'll push a PR in a few minutes.

**Comment by avoidwork** [comment]
@castarco as per mentioned above, this issue is not due to misconfiguration of tiny-lru, but of the tools you're relying on. The changes made to package.json are based on the npm documentation, and not ad-hoc tools people cooked up to deal with a shitty package manager (npm IMO is not great).

**Comment by avoidwork** [comment]
Resolved the core issue with https://github.com/avoidwork/tiny-lru/commit/345cde554aacc763325904b41822ad95640c2875#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R20

![Screenshot 2023-10-10 065409](https://github.com/avoidwork/tiny-lru/assets/369698/5403bf84-a94a-484c-9c52-5e08f540838c)

**Comment by naugtur** [comment]
> `main` is simply the default file to load, if an extension is not provided it goes through its enums. the `.cjs` was used in `10.x.x` and now that `esm` is viable it's time to let the tooling sort out this giant mess.
> 
> Upgrade your toolchain if you have a problem, or switch to tools that work.
> 
> This works with just pure node. Anything that's breaking is outside of this project.

There's multitude of engines and `main` is for the older or simpler of those. Most engines read exports. The ones that don't support exports in package.json are often also not aware of mjs and cjs extensions. 
It works in node because node no longer relies on the main field when you add exports.

It's not a matter of configuration by the user but mostly built-in support or not.

`main` should contain the extension if you wish to support non-esm runtimes and keep the .js file esm

**Comment by avoidwork** [comment]
That matters from your perspective because of choices you've made, but this code has always only targeted node and browser because I just don't care to chase trends over years.

If you need a change for a tool, make a PR and explain why it's needed.

**Comment by avoidwork** [comment]
Name the tool if such a PR please.
