### ISSUE TITLE
Why use the "in" operator instead of "!== undefined"?

### ISSUE THREAD

**Issue by woitechen** [avoidwork/tiny-lru#12]
https://github.com/avoidwork/tiny-lru/blob/bbbfacbef590f82b5f5221e0b1d1936e1196a8b5/src/lru.js#L74

**Comment by avoidwork** [comment]
@woitechen it's significantly faster, and the there's no prototype extension so the extra ops of other approaches don't benefit you.

**Comment by woitechen** [comment]
@avoidwork, [this](https://jsperf.com/array-indexof-vs-object-s-in-operator/4) test on Chrome 70.0.3538 shows that "typeof obj['key'] !== 'undefined'" is about 5x faster than the 'in' operator.

**Comment by avoidwork** [comment]
👍 validating claims is always a good thing
