### ISSUE TITLE
#.get method not mutating previous pointers

### ISSUE THREAD

**Issue by Yomguithereal** [avoidwork/tiny-lru#15]
Hello @avoidwork,

Sorry to bother you but reading your code, I am struggling to understand how [those](https://github.com/avoidwork/tiny-lru/blob/master/src/lru.js#L49-L63) lines can avoid modifying prev pointers at all. Am I missing something obvious here?

**Comment by avoidwork** [comment]
@Yomguithereal are or aren't?

**Comment by Yomguithereal** [comment]
Those lines are not touching previous pointers. They are not modifying much pointers to splay keys on top of the chain.

**Comment by avoidwork** [comment]
ah, test gap. i had planned on creating a `link()` but reverted due to `irl stuff`; fixing now by reverting (partially) and adding tests to validate cache item state

**Comment by avoidwork** [comment]
I've made eviction slightly cheaper with a similar approach to this change; and i've updated bench-lru with 3.0.3.
