### ISSUE TITLE
Rename remove to delete?

### ISSUE THREAD

**Issue by adjourn** [avoidwork/tiny-lru#17]
What do you think?

It would be compatible with Map API and we could easily swap caches without any huge rewrites. Not only that, we could use this library with other libraries that use Map as default cache, e.g wonderful [dataloader](https://github.com/facebook/dataloader).

Required methods are `get`, `set`, `delete` and `clear`.

PS! I haven't had time to test modified `tiny-lru` with `dataloader` yet but same API is still awesome IMO.

**Comment by adjourn** [comment]
Oopsie, I was too hasty this time. LRU class has `delete` method but it's undocumented. Is it safe to use? 

Im going to keep this issue open until I get confirmation. There must be a reason it's undocumented..

**Comment by avoidwork** [comment]
@adjourn i think it was added for interop with lowdash a while a go. I'll add it to the README next time a change lands.
