### ISSUE TITLE
Module is broken

### ISSUE THREAD

**Issue by GeKorm** [avoidwork/tiny-lru#19]
Hi. The last version that works with modules `import lru from 'tiny-lru` when bundling with webpack is 1.6.4  
As far as I can tell the compilation method/target has changed since version 2.0.0; I haven't found a way to import tiny-lru as a module since then.
 
Thank you

**Comment by avoidwork** [comment]
Module is not broken, it just doesn't target `import`.

**Comment by GeKorm** [comment]
@avoidwork Mind sharing the reason behind the change in v2 please? Was it just to simplify the build process?

I'm asking to see how to best approach this. I'm assuming you want to keep the es6+ output based on [this commit](https://github.com/avoidwork/tiny-lru/commit/7a3c9a61947fae562e97a9bf71cd24cf25e7394e#diff-35b4a816e0441e6a375cd925af50752cL28) removing the `env` preset?

**Comment by GeKorm** [comment]
Definitely needed for the browser!

**Comment by avoidwork** [comment]
definitely not. no mobile browser requires it, and no browser that's "secure" (aka, no ie11 or edge - both have been sunset)... leaving webkit & chromium based browsers.

running a browser that requires babel is a smell of opsec issues.

**Comment by avoidwork** [comment]
or... babel is the new jquery

**Comment by avoidwork** [comment]
that said, if you can resolve the requirement of an export being top level and the factory assignment it should work out for your use case. again, babel is not required here :)

**Comment by GeKorm** [comment]
I hear what you're saying, and I wish it was up to us to upgrade our users' browsers, but unfortunately it's not. Would you mind a `tiny-lru.es5.js` living in lib/ ?

**Comment by avoidwork** [comment]
sure

**Comment by trycontrolmymind** [comment]
Solve it like this

```
yarn add tiny-lru@6

webpackConfig.resolve = {
 ...your config resolve...
  alias: {
    "tiny-lru": path.join(process.cwd(), "/node_modules/tiny-lru"),
,
  }
};
```
