### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by Beanow** [avoidwork/tiny-lru#21]
Issue name inspired by: https://keepachangelog.com/en/1.0.0/

Either way my point is. I just ran `npm outdated` and found out I'm on `tiny-lru@^1.6.1` and we're now at `6.x`. I have no idea what changed, what makes it breaking and how to migrate.

A clear changelog would be great for this.

**Comment by avoidwork** [comment]
I used to keep changelogs. You can compare version tags and look at the readme to see what changed at a high level.

**Comment by Beanow** [comment]
For a small package I use as a sub-sub-sub dependency in several projects, that's rather time consuming. If all of several dozens of similar dependencies did this it would quickly spiral out of control. Hence the request. In my opinion it's necessary time saver to keep updated.

**Comment by avoidwork** [comment]
It's just repackaging the git history into segments, which are already segmented via the tags.

https://github.com/avoidwork/tiny-lru/compare/1.4...master

Changelog generators are not a real solution, only having a tech writer on staff is, and I don't have one.

**Comment by avoidwork** [comment]
If you have a preferred generator, you can open a PR.
