### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'value')

### ISSUE THREAD

**Issue by korzo** [avoidwork/tiny-lru#233]
```ts
import { LRU } from 'tiny-lru';

const cache = new LRU(1000, 0, false);
cache.set('foo', 'bar', true);
// TypeError: Cannot set properties of undefined (setting 'value')
```
There is a missing check if item is not undefined on line 117 
https://github.com/avoidwork/tiny-lru/blob/8911cb6ac1241e77472a0d98d399ba3013822774/src/lru.js#L113-L117

**Comment by avoidwork** [comment]
@korzo you're passing `true` for `bypass` which tells it to skip the check.
