### ISSUE TITLE
Wrong TypeScript type definitions

### ISSUE THREAD

**Issue by fox1t** [avoidwork/tiny-lru#30]
Hi. I've just updated the package to the latest version and got this TS error:`Value of type 'typeof Lru' is not callable. Did you mean to include 'new'`

TS is tricked to think that the class is exported instead of the factory function. 
In https://github.com/avoidwork/tiny-lru/blob/master/src/lru.js#L137 we can see that the factory is exported, instead of the constructor as written here https://github.com/avoidwork/tiny-lru/blob/master/tiny-lru.d.ts#L2

Let me know if you need help with this.

**Comment by fox1t** [comment]
For reference this fixes the issue:
```typescript
declare module 'tiny-lru' {
  class Lru<T = any> {
    constructor(max?: number, ttl?: number)

    public has(key: string): boolean
    public get(key: string): T
    public set(key: string, value: T, bypass?: boolean): this
    public clear(): this
    public delete(key: string): this
    public evict(): this
    public keys(): string[]
  }
  export default function factory<T = any>(max?: number, ttl?: number): Lru<T>
}
```

**Comment by osdevisnot** [comment]
Imo, it's always a hassle maintaining the definitions by hand. Other than high risk of being outdated, it's time consuming to update them each release.

I'll put up a PR to see if we can automate this.

**Comment by fox1t** [comment]
@osdevisnot I agree with you, however `tiny-lru` exposes really a tiny surface as public API. 
How are you going to automate a types declaration?

**Comment by osdevisnot** [comment]
@fox1t Attempting this in #31 - Let me know your thoughts.

**Comment by fox1t** [comment]
Are there any news on this? I think that it is blocking for everyone using TS. If help is needed, I could provide it!

**Comment by avoidwork** [comment]
@fox1t  just open a PR with your type change to address your issue; the other PR as a change to typescript source isn't wanted.

**Comment by avoidwork** [comment]
@fox1t ping me on twitter (@jasonmulligan) if i miss another PR; my work is quite hectic atm and oss stuff doesn't get any attention.

**Comment by avoidwork** [comment]
Closing due to #33 merging & releasing.
