### ISSUE TITLE
IE 11 Support

### ISSUE THREAD

**Issue by WayneEllery** [avoidwork/tiny-lru#35]
Currently this package is published as ES6. ES6 is not supported in IE so it means that Babel needs to have client app configured to compile the package in node_modules in order to support IE11. It's best practice to ship ES5: https://github.com/rollup/rollup/wiki/pkg.module#wait-it-just-means-import-and-export--not-other-future-javascript-features

**Comment by osdevisnot** [comment]
It should be available as ES5 package as well, see https://unpkg.com/browse/tiny-lru@7.0.2/lib/

I believe you'll need to import it as a module with specific path: tinu-lru/lib/tinu-lru

TBH, for ie 11, you would almost use some sort of build step, in which case your bundler should automatically pick up a .cjs.js version

**Comment by WayneEllery** [comment]
Thanks for getting back so quick. The bundler would use the module field for the browser bundle which is pointing to `lib/tiny-lru.esm.js` but this contains ES6. It should be using only ESM exports/imports but it should be ES5 as babel won't transpile the module node_modules folder.

**Comment by WayneEllery** [comment]
The reason why you would want the bundler to use module as allowed to the browser field is it supports esm so it will support tree shaking (not applicable in this case) but the code is still running in the browser so it needs to be ES5.

**Comment by avoidwork** [comment]
https://www.zdnet.com/article/microsoft-security-chief-ie-is-not-a-browser-so-stop-using-it-as-your-default/ If you need that es5 output just create a wrapper project that includes this one & creates the output you need.
