### ISSUE TITLE
Code would be smaller if get() took a supplier

### ISSUE THREAD

**Issue by nealeu** [avoidwork/tiny-lru#44]
Hi,

When using `tiny-lru`, the `get()` method not taking a supplier means I have to write unnecessary code and I think you'd agree I'd rather _avoidwork_.

So, instead of having to write:

```
let result = get(key)
 if (! result) {
   result = doMySlowThing(key);
   set(key, result);
}
```
I'd rather just write:
```
const result = get(key, () => doMySlowThing(key));
```

So the API for `get()` could have supplier as an optional arg:

    get(key: string, supplier?: () => T): T | undefined

**Comment by avoidwork** [comment]
That's not a cache concern.

**Comment by avoidwork** [comment]
If you want this feature open a PR and also prove with deoptigate (or whatever can work with IR) to show this isn't a deopt. There's only 1 deopt in the code atm.

**Comment by nealeu** [comment]
Thanks Jason, but I'll put my efforts into contributing to projects where the lead doesn't close a ticket with a blunt 1-liner.

**Comment by avoidwork** [comment]
You made the mistake of thinking i care about your code.
