### ISSUE TITLE
The 'expiry' property of cache items are recomputed each 'get()' or 'set()'

### ISSUE THREAD

**Issue by avoidwork** [avoidwork/tiny-lru#48]
There's no reason the 'ttl' is required to reassign the values in the two methods; it should be set once. If 'ttl' attribute changes over time, the cache would need to be repopulated (i believe original goal was keeping things in cache). Relates to goal of #47.

**Comment by rluvaton** [comment]
The `expiry` property is not been recompute on `get` only on `set` because the `get` function pass `bypass` `true` to the `set` function which means that the `expiry` property don't get recomputed

**Comment by avoidwork** [comment]
It's an optional parameter so it's possible. If it's possible, it's happening.
