### ISSUE TITLE
Changelog's links 404

### ISSUE THREAD

**Issue by Eomm** [avoidwork/tiny-lru#51]
Hi,
all the changelog's links are broken:

https://github.com/avoidwork/tiny-lru/blob/master/CHANGELOG.md

They bring you to: `https://github.com//avoidwork/tiny-lru.git/commit/f16fc2e77fb0bae5f2067b030aa1368c2e1f98a5`

Instead of `https://github.com/avoidwork/tiny-lru/commit/f16fc2e`

The issues are

- the double slash
- the `.git` as repo name

**Comment by avoidwork** [comment]
The value is generated by git when you clone the origin, so a bug in git? The repo has never had a double slash in it's URL.

**Comment by avoidwork** [comment]
I think the error is coming from webstorm's clone via ssh.
