### ISSUE TITLE
TypeScript definitions are missing in 9.0.0

### ISSUE THREAD

**Issue by ardatan** [avoidwork/tiny-lru#54]
Hi @avoidwork !
First of all, thanks for your effort on this project. We use this awesome package a lot in our projects and love it!
While upgrading from 8.x, I realized TS definitions are no longer available in 9.0.0 release.
https://app.renovatebot.com/package-diff?name=tiny-lru&from=8.0.2&to=9.0.0

**Comment by avoidwork** [comment]
I just put the .d.ts back in root with 9.0.1.
