### ISSUE TITLE
TypeError: Cannot access private method

### ISSUE THREAD

**Issue by kiwionly** [avoidwork/tiny-lru#60]
Hello, 

I am using version 10.0.1 and encounter this issue when call get(), below show error in my browser console:

```
chunk-VNXF6W56.js?v=202f4f6a:39 Uncaught (in promise) TypeError: Cannot access private method
    at __accessCheck (chunk-VNXF6W56.js?v=202f4f6a:39:11)
    at __privateMethod (chunk-VNXF6W56.js?v=202f4f6a:47:3)
    at Proxy.get (tiny-lru.esm.js:80:7)
    at Object.<anonymous> (main.js:80:23)
```
which turn out to be here:

![image](https://user-images.githubusercontent.com/174617/214550793-ad094169-206f-424d-af58-a70fc067b1dd.png)

however, that is no issue at version 9.0.3

**Comment by avoidwork** [comment]
Hi,

What version of node are you using? it looks like i didn't bump the 'engines' value in package.json when releasing 10.0.0 which marks that method as private.

**Comment by kiwionly** [comment]
Hi, finally I had some time to show the errors, I am tiny -lru in vuex:

```  
const store = createStore({
	
	state: {
		cache: lru(200)
	},
	
	getters: {		
		cache: (state) => (key) => {						
			return state.cache.get(key);
		},
	},
```

with tiny -lru version 9.0.3, it working fine. However, when I upgrade to version 10+, I encounter error like this

![image](https://user-images.githubusercontent.com/174617/229751731-e8286a67-e1bf-4afa-98fe-6044309756c9.png)

![image](https://user-images.githubusercontent.com/174617/229751988-7938c690-d39c-403c-99e4-f6d1b691eb12.png)

Hope this help !

**Comment by avoidwork** [comment]
Hi, the difference is a private method on the LRU class; the error implies you're using a version of node or javascript (browser) that's behind (based on caniuse.com) for private methods; see https://caniuse.com/mdn-javascript_classes_private_class_fields

If you can't change the version of node/browser, then you have to use 9.x.x; there's no way to make it work.

**Comment by avoidwork** [comment]
The commit 3 weeks ago updated the engine version reflect the requirement of supporting private fields.

**Comment by avoidwork** [comment]
If you have a Proxy calling the cache, is the context of the call changing? what is "this" via breakpoint at that line (81)? it _should_ be `LRU`, if it's the `Proxy` you want to either bind the get/set or .call() the methods; this is outside of the LRU cache entirely.

**Comment by kiwionly** [comment]
I try to print out lru object and it actually look like this : 

![image](https://user-images.githubusercontent.com/174617/229986790-fbc0b8c9-2e8e-4816-a37f-207ec1da4387.png)

![image](https://user-images.githubusercontent.com/174617/229987120-fb245187-c5a9-468c-bfd7-cb3ac8b879c7.png)


I assume the [target] should have a `has` or `get` method ? ( since I not an expert on JS field, I could only try simple way to pinpoint issue )

**Comment by avoidwork** [comment]
can you share the code that creates the proxy; the issue is the usage of the proxy.

**Comment by avoidwork** [comment]
The proxy getter needs to rewritten; however you shouldn't use a proxy on things with private fields. They're also really slow.

```javascript
class Example {
    #world = "world";
    hello(){
        console.log(`Hello ${this.#world}`);
    }
}

const exampleProxy = new Proxy(new Example(),   {
    has: function (obj, prop) {
        return prop in obj;
    },
    get(target, prop, receiver) {
        return (params) => {
            return target[prop](params);
        }
    },
    set: function (obj, prop, value) {
        obj[prop] = value;
        return this;
    }
});
```

![Screenshot 2023-04-05 075730](https://user-images.githubusercontent.com/369698/230073741-6a13a3d0-deba-4298-bed8-602fb40de82a.png)

**Comment by avoidwork** [comment]
In the future please provide a sample like this; chance of me trying to recreate your issue is very small.

**Comment by kiwionly** [comment]
I use in [vuex ](https://vuex.vuejs.org/), a bit complicated to show code because it also had html ( My code is running in browser ).

The code roughly like this 
```JavaScript

import { lru } from "tiny-lru"

const store = createStore({
	
	state: {
		cache: lru(200)
	},
	
	getters: {		
		get: (state) => (key) => {						
			return state.cache.get(key);
		},
	},
	
	mutations: {		
		set(state, payload) {			
			state.cache.set(payload.key, payload.value);
		}		
	}
})

// usage

var cache = this.$store.getters.get(key);
```
This had no issue on tiny-lru version 9.0.3 but not version above 9.0.3.

**Comment by avoidwork** [comment]
I know, because at 10.0.0 it became a private method and your proxy code doesn't handle that. So your options are to use 9.x.x or update your code to handle privates.

**Comment by kiwionly** [comment]
i see, thanks !

**Comment by avoidwork** [comment]
Might be worth opening an issue with vuex if you can't override the proxy.

**Comment by kiwionly** [comment]
I will stick to version 9 since I not have clear idea of how proxy and private method work.

**Comment by avoidwork** [comment]
I'm curious about the scope of this issue, proxies affecting interoperability wasn't a consideration when I set the field to private.

**Comment by avoidwork** [comment]
@kiwionly try 11.0.0; the private field was replaced with the same function in scope so that should work with the proxy.

**Comment by kiwionly** [comment]
@avoidwork I just upgrade to version 11 and it work as expected, thanks !
